version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
    ports:
      - 3306:3306
    volumes:
      - app_postgre:/var/lib/postgresql/data
    restart: always

  api:
    tty: true
    depends_on:
      - db
    build: ./docker/api
    ports:
      - 3000:3000
    volumes:
      - ./api:/app_name
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"

  client:
    build: ./docker/client/
    environment:
      - NODE_ENV=production node server.js
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/usr/src/app
    command: sh -c 'yarn dev'
    ports:
      - 8000:3000
volumes:
  app_postgre:
    external: true
